<?php

namespace App\Http\Controllers\Api\Subscriptions;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CreateController extends Controller
{
    public function createProduct(Request $request)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/catalogs/products');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"name\": \"Service ContactMajor\",\n  \"description\": \"Base de Contact Musique Ultime\",\n  \"type\": \"SERVICE\",\n  \"category\": \"AGENCIES\",\n  \"image_url\": \"https://www.contactmajor.com/static/android-icon-192x192-fc5a0a5ae2376347f14b59d05847d8a3.png\",\n  \"home_url\": \"https://www.contactmajor.com\"\n}");

        $headers = array();
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'Authorization: Bearer A21AAFkuNFaqi3wZibyGa00h-jw-2dHCFRHuGE_2fwSUuKPR0pw4vkQy8cJ8tmZ8EbdMipTVdklSDNY7MDskqFtrVo9CMQNlA';
        $headers[] = 'Paypal-Request-Id: DLD7TS76EYX4C';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;
    }

    public function getToken()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/oauth2/token');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
        curl_setopt($ch, CURLOPT_USERPWD, 'AW7puiqSy4C6HSH6_PXmNLgjSLEY8YmHOKKqSXFduSkQ4b9MpRxLuh86duBi185BVEICAdE56v-jcRc_' . ':' . 'EORhMR33SdZLIICSFQccepXRyByy5zFD_tuZ6lSwVrSytQEBYNjyBSkEhVyyc-S-qx34dhNh74OFFYvx');

        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Accept-Language: en_US';
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return response()->json($result);
    }

    public function createPlan()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/billing/plans');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n      \"product_id\": \"PROD-2JU27149U49338147\",\n      \"name\": \"Basic Plan\",\n      \"description\": \"Basic plan\",\n      \"billing_cycles\": [\n        {\n          \"frequency\": {\n            \"interval_unit\": \"DAY\",\n            \"interval_count\": 1\n          },\n          \"tenure_type\": \"TRIAL\",\n          \"sequence\": 1,\n          \"total_cycles\": 1\n        },\n        {\n          \"frequency\": {\n            \"interval_unit\": \"YEAR\",\n            \"interval_count\": 1\n          },\n          \"tenure_type\": \"REGULAR\",\n          \"sequence\": 1,\n          \"total_cycles\": 0,\n          \"pricing_scheme\": {\n            \"fixed_price\": {\n              \"value\": \"85\",\n              \"currency_code\": \"EUR\"\n            }\n          }\n        }\n      ],\n      \"payment_preferences\": {\n        \"auto_bill_outstanding\": true,\n        \"setup_fee\": {\n          \"value\": \"85\",\n          \"currency_code\": \"EUR\"\n        },\n        \"setup_fee_failure_action\": \"CONTINUE\",\n        \"payment_failure_threshold\": 3\n      },\n      \"taxes\": {\n        \"percentage\": \"10\",\n        \"inclusive\": false\n      }\n    }");

        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Authorization: Bearer A21AAFkuNFaqi3wZibyGa00h-jw-2dHCFRHuGE_2fwSUuKPR0pw4vkQy8cJ8tmZ8EbdMipTVdklSDNY7MDskqFtrVo9CMQNlA';
        $headers[] = 'Paypal-Request-Id: DLD7TS76EYX4C';
        $headers[] = 'Prefer: return=representation';
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;
    }
}
